### ISSUE TITLE
Better handle data retrieved from archive

### ISSUE THREAD

**Issue by NichtJens** [paulscherrerinstitute/jungfrau_utils#8]
JU currently does not handle data retrieved from archive very gracefully.

See original report here:
https://github.com/paulscherrerinstitute/sf_datafiles/issues/14

The automatic search for gain and pedestal file fails due to the data being retrieved into `/das/work`. Thus, the logic here needs adjustment:

- https://github.com/paulscherrerinstitute/jungfrau_utils/blob/master/jungfrau_utils/swissfel_helpers.py#L26
- https://github.com/paulscherrerinstitute/jungfrau_utils/blob/master/jungfrau_utils/swissfel_helpers.py#L63

Additionally, we might need to outline for the users where they have to put the pedestal data after retrieving it. I am not sure this is automatically correct already. We should check. Even if it's automatically correct already, they need to know that they also have to retrieve that dataset.

**Comment by ivan-usov** [comment]
Indeed, the support for automatic gain/pedestal file search doesn't exist for data retrieved from archive, however, it makes a lot of sense to add it, as more and more files will be analyzed that way in the future. 

The check whether a file path starts with "/sf" was introduced merely to detect cases when files were copied elsewhere and the folder structure is not known anymore. Talking to @ozerov-d , after retrieve the folder structure should remain the same, but have a prefix, i.e. "/das/work/pXX/pXXXXX/retrieve" in case of psi ra. So, a solution would be to search default gain/pedestal paths as a sub-string within the full path of the retrieved file, and if that folder(s) exist, locate the most appropriate pedestal file there.
