### ISSUE TITLE
Geometry not being applied to older files?

### ISSUE THREAD

**Issue by asteppke** [paulscherrerinstitute/jungfrau_utils#9]
Hello, 

When trying to look at older Jungfrau data it looks as if the geometry is not being applied. I don't know why this should be the case here. 

The test case (looking into the ring images from Cristallina):

````python
import jungfrau_utils as ju
print(ju.__version__)
````
yields the recent
````
3.14.4
````

````python
juf = ju.File("/sf/cristallina/data/p19739/raw/run0202/data/acq0001.JF16T03V01.h5", geometry=True) 

print(juf.geometry)
print(juf[0].shape)
````
yields

````
True
(1554, 1030)
````

and the geometry looks OK:

`ju.geometry.detector_geometry["JF16T03V01"]` gives `DetectorGeometry(origin_y=(0, 550, 1100), origin_x=(0, 0, 0), mod_rot90=(0, 0, 0), is_stripsel=False, det_rot90=0)`

When loading more recent data
````python
juf = ju.File("/sf/cristallina/data/p21516/raw/run0009/data/acq0001.JF16T03V01.h5", geometry=True) 

print(juf.geometry)
print(juf[0].shape)
````
gives

````
True
(1614, 1030)
````

Is there something else that needs to be provided so that the geometry is applied to older data as well?

**Comment by ivan-usov** [comment]
Hi @asteppke 
Thanks for drawing attention to this issue. The files you're opening are already processed and with geometry applied, so providing `geometry` parameter has no effect, as data is already "frozen" in that geometry. The older file was converted using an older version of jungfrau_utils, which had a narrower gap between the modules. While the newer version of jungfrau_utils has it fixed.

If you try the "actual" raw data (.../data/... -> .../raw_data/...), located in:
```
/sf/cristallina/data/p19739/raw/run0202/raw_data/acq0001.JF16T03V01.h5
/sf/cristallina/data/p21516/raw/run0009/raw_data/acq0001.JF16T03V01.h5
```
for corresponding files, you should be able to see the identical and correct geometry of (1614, 1030).

What seems to be very unfortunate is that jungfrau_utils doesn't warn that `geometry` parameter has no effect when opening an already processed file. It only does it when trying to modify that parameter after the file is open, i.e.
```
>>> juf = ju.File("<already processed file path>", geometry=True)  # Works, but should warn already here!
>>> juf.geometry = False  # Correctly warns
The file is already processed, setting 'geometry' has no effect.
```
This needs a fix.

**Comment by asteppke** [comment]
Hi @ivan-usov 
Thank you for your instant reply and the tips.

I was confused because we have raw data in 
`/sf/cristallina/data/p21516/raw/run0009/acq0001.JF16T03V01.h5`
but as you pointed out already processed data in 
`/sf/cristallina/data/p19739/raw/run0202/acq0001.JF16T03V01.h5`.

It would indeed be helpful if jungfrau_utils would warn, especially in the case that the geometry in the processed file does not correspond to the currently assumed geometry.
